### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [renatapro/zadanie10.2#1]
- [x] popraw stylowanie karuzeli, aby byla wysrodkowana na stronie niezaleznie od rozmiarow okna przegladarki - aktualnie ustawiasz pozycje na sztywno, co nie jest wysrodkowaniem
- [x] sprobuj zmierzyc sie z punktami dla ambitnych :)

**Comment by renatapro** [comment]
-nie wiem jak poradzić sobie z tymi kontrolkami, żeby to chodziło jak trzeba

- plik html to trochę wzorowałam się na tym z bootstrapa i nie jestem pewna czy jest dobrze zrobiony

- proszę o jakieś wskazówki w jakim kierunku mam działać:)

**Comment by zdolny** [comment]
bardzo dobrze :)
kontrolki sobie podarujemy bo teraz zbyt duzo czasu by to zabralo, generalnie musialabyc odczytywac wartosc atrybutu `data-slide-to` i przewinac do odpowiedniego slajdu

Dlatego na ten moment:
- [ ] usun/ukryj zabawy z kontrolkami
- [ ] zmien nazwe funkcji `changeSlide` na `changeSlideNext` - skoro mamy `changeSlidePrev` to w ten sposob bedzie bardziej spojne i czytelne

**Comment by zdolny** [comment]
obecnie jak dluzej poklikasz po karulezeli to okazuje sie, ze interwal automatycznego przewijania slajdow gryzie sie z przewijaniem recznym, co prowadzi do dziwnych zachowan karuzeli.

Proponuje, zeby po kliknieciu w ktoras ze strzalek wylaczac ten interwal, zeby od tego momentu przewijanie bylo tylko po kliku. Mozesz wyczyscic interwal za pomoca `clearInterval()` - zorientuj sie jak go uzyc :)

**Comment by renatapro** [comment]
może teraz będzie dobrze:)
